-- table tasks
CREATE TABLE aulas (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    tipo INTEGER NOT NULL,
    nombre VARCHAR(200) NOT NULL,
);

CREATE TABLE detaulas (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    aula INTEGER NOT NULL,
    fechainicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fechafinal TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    done BOOLEAN NOT NULL DEFAULT 0,
    motivo VARCHAR(200) NOT NULL,
    FOREIGN KEY (aula) REFERENCES aulas(id)
);
